// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/8/2026, 4:25:35 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/mac/Desktop/milleServices/milleService-backoffice/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/milleServices/milleService-backoffice/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/milleServices/milleService-backoffice/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/milleServices/milleService-backoffice/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/milleServices/milleService-backoffice/app/plugins/**/*.{js,ts,mjs}","/Users/mac/Desktop/milleServices/milleService-backoffice/app/composables/**/*.{js,ts,mjs}","/Users/mac/Desktop/milleServices/milleService-backoffice/app/utils/**/*.{js,ts,mjs}","/Users/mac/Desktop/milleServices/milleService-backoffice/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/milleServices/milleService-backoffice/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/milleServices/milleService-backoffice/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Desktop/milleServices/milleService-backoffice/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;